//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BurovAV {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BurovAV() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortAI.Data.BurovAV.BurovAV", typeof(BurovAV).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About myself.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aleksey Burov.
        /// </summary>
        public static string BurovAleksey {
            get {
                return ResourceManager.GetString("BurovAleksey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download app.
        /// </summary>
        public static string DownloadApp {
            get {
                return ResourceManager.GetString("DownloadApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the page.
        /// </summary>
        public static string GoToPage {
            get {
                return ResourceManager.GetString("GoToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My name is Aleksey. I like to program and I am constantly developing in this direction. My attraction to programming began with computer science lessons at school, then I went to study at the institute at the faculty of computer science. &lt;br /&gt;
        ///    After graduation, he returned to his hometown and began to look for work. In a small town, it’s harder to find a job, especially as a programmer. Then I decided not to waste time and went to work as an electronic engineer. Since there was enough free time, I dev [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MyBiography {
            get {
                return ResourceManager.GetString("MyBiography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A good screensaver turned out at the time of studying the engine. Capturing a frame on Blitz3d is very stressful for the system, but modern PCs can do it. Most of all I remember the development of a calendar with the ability to turn over the months..
        /// </summary>
        public static string MyProjectBlitzDemo1 {
            get {
                return ResourceManager.GetString("MyProjectBlitzDemo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I decided to develop labyrinths when it was boring at work. I decided to entertain my colleagues, but it turned out to be the most fun for me when I realized that to quickly build maps on the console IDE, write your own editor)
        ///                It was an interesting experience and a good result..
        /// </summary>
        public static string MyProjectBlitzDemo2 {
            get {
                return ResourceManager.GetString("MyProjectBlitzDemo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project appeared when I wanted to congratulate my girlfriend on a virtual postcard. I decided to generate free flowering flowers. Simulated the fall of the petals by the controller (manual particle generator). I liked to develop a system of stem and flower growth based on the principle of heritage and changing characteristics..
        /// </summary>
        public static string MyProjectBlitzDemo3 {
            get {
                return ResourceManager.GetString("MyProjectBlitzDemo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is my last and largest development on the Blitz3D engine. Many interesting solutions were invented here, it is a pity that the engine is outdated. In this project, I developed a change of day and night, a system of plant growth and soil fertility, LOD from a distance, the use of shaders and much more..
        /// </summary>
        public static string MyProjectBlitzDemo4 {
            get {
                return ResourceManager.GetString("MyProjectBlitzDemo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        public static string Repo {
            get {
                return ResourceManager.GetString("Repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It became interesting for me to try RestAPI, I chose the topic - Search for films. Because it is clear. In this project, I used many technologies new to me, these were: middleware, bootstrap, localization (special thanks to the developers of the &lt;a href=&apos;https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager#review-details&apos;&gt;plugin&lt;/a&gt;), multi-threaded downloading of a collection of films. I used tmdb api, it has a limitation (1 request contains a maximum of 30 films) the use of multithre [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RestAPIDemo1 {
            get {
                return ResourceManager.GetString("RestAPIDemo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show mail.
        /// </summary>
        public static string ShowMail {
            get {
                return ResourceManager.GetString("ShowMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show phone.
        /// </summary>
        public static string ShowPhone {
            get {
                return ResourceManager.GetString("ShowPhone", resourceCulture);
            }
        }
    }
}
